name: Container
on: push

jobs:
  docker-step:
    runs-on: ubuntu-latest
    # Dockerfile と類似
    container:
      image: docker://linuxbrew/brew
    # # docker-compose.yml と同構造
    # services:
    #   app:
    #     image: alialaa17/node-api
    #     ports:
    #       - "3001:3000"
    #   mongo:
    #     image: mongo
    #     ports:
    #       - "27017:27017"
    steps:
      # step with Docker
      - name: Step with docker
        uses: docker://linuxbrew/brew
        with:
            entrypoint: /bin/echo
            args: Hello World
      - uses: actions/checkout@v2
      - name: Run a Script
        uses: docker://linuxbrew/brew
        with:
            entrypoint: ./config/docker/script.sh
            args: Hello World
